# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: abella.dev
email: carlosg.abella@gmail.com

#write html inside the double quotes to display in jumbotron
description: "<h3></h3><h1>Log Book</h1><h3>Notes, thoughts and other experiences in my techie life.</h3>"

domain: carlosabella.github.io       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://carlosabella.github.io  # the base hostname and protocol for your site, e.g. http://example.com
baseurl: /logbook.github.io        # place folder name if the site is served in a subfolder
repository: carlosabella/logbook.github.io
twitter_username: abella_carlos
github_username:  carlosabella

# Build settings
markdown: kramdown
